# Generated by Django 4.2.8 on 2024-06-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_name',
            field=models.CharField(max_length=10),
        ),
    ]
