# Generated by Django 4.2.8 on 2024-06-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_driver_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='from_destination',
            field=models.CharField(choices=[('Vijayawada', 'Vijayawada'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Islamabad', 'Islamabad'), ('Guntur', 'Guntur')], max_length=20),
        ),
        migrations.AlterField(
            model_name='destination',
            name='to_destination',
            field=models.CharField(choices=[('Vijayawada', 'Vijayawada'), ('Goa', 'Goa'), ('Delhi', 'Delhi'), ('Hyderabad', 'Hyderabad'), ('Islamabad', 'Islamabad'), ('Guntur', 'Guntur')], max_length=20),
        ),
    ]
